name: gym-http-api
version: '0.1.0.0'
description: Haskell bindings for the OpenAI gym API
category: Web, Learning Environments
author: Daniel Lucsanszky, Sam Stites
maintainer: dl3913@ic.ac.uk, sam@stites.io
license: MIT
license-file: LICENSE
github: stites/gym-http-api/binding-hs
synopsis: REST client to the gym-http-api project
description:
  This library provides a REST client to the gym open-source library. gym-http-api itself provides a
  <https://github.com/openai/gym-http-api/blob/master/gym_http_server.py python-based REST> server
  to the gym open-source library, allowing development in languages other than python.


  Note that the <https://github.com/openai/gym-http-api/ openai/gym-http-api> is a monorepo of all
  language-clients. This hackage library tracks <https://github.com/stites/gym-http-api/ stites/gym-http-api>
  which is the actively-maintained haskell fork.
extra-source-files:
  - README.md
  - TODO.md
  - CHANGELOG.md

default-extensions:
  - OverloadedStrings

dependencies:
  - base           >= 4.7 && < 5
  - servant-client >= 0.9
  - containers     >= 0.5
  - text           >= 1.2

library:
  source-dirs: src
  dependencies:
  - aeson                >= 1.0
  - servant              >= 0.9
  - servant-lucid        >= 0.7

executables:
  example:
    main: Agent.hs
    source-dirs: examples
    dependencies:
    - gym-http-api
    - http-client    >= 0.5
    - exceptions     >= 0.8

