name: gym-http-api
version: '0.1.0.0'
description: Haskell bindings for the OpenAI gym API
category: Web, Learning Environments
author: Daniel Lucsanszky, Sam Stites, Tycho Grouwstra
maintainer: dl3913@ic.ac.uk, sam@stites.io, tychogrouwstra@gmail.com
license: MIT
github: stites/gym-http-api/binding-hs
synopsis: REST client to the gym-http-api project
description:
  This library provides a REST client to the gym open-source library. gym-http-api itself provides a
  <https://github.com/openai/gym-http-api/blob/master/gym_http_server.py python-based REST> server
  to the gym open-source library, allowing development in languages other than python.


  Note that the <https://github.com/openai/gym-http-api/ openai/gym-http-api> is a monorepo of all
  language-clients. This hackage library tracks <https://github.com/stites/gym-http-api/ stites/gym-http-api>
  which is the actively-maintained haskell fork.
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - UnicodeSyntax
  - QuasiQuotes

dependencies:
  - base >= 4.11.1.0
  - servant-client >= 0.13.0.1
  - containers >= 0.5.11.0
  - text >= 1.2.3.0
  - base-unicode-symbols >= 0.2.2.4
  - containers-unicode-symbols >= 0.3.1.1
  - stylish-haskell >= 0.9.2.0
  - hlint >= 2.1.5

library:
  source-dirs: src
  dependencies:
  - aeson >= 1.3.1.1
  - servant >= 0.13.0.1
  - servant-lucid >= 0.8
  - invertible-syntax >= 0.2.1
  - unordered-containers >= 0.2.9.0
  - base >= 4.11.1.0
  - dump >= 0.2.8
  - scientific >= 0.3.6.2
  - random >= 1.1
  - vector >= 0.12.0.1

executables:
  example:
    main: Main.hs
    source-dirs: examples
    dependencies:
    - gym-http-api # >= 0.1.0.0
    - http-client >= 0.5.12.1
    - exceptions >= 0.10.0
    - mtl >= 2.2.2
    - cmdargs >= 0.10.20
    - extra >= 1.6.6
    - transformers-base >= 0.4.5.2
    - lifted-base >= 0.2.3.12
    - monad-control >= 1.0.2.3
    - hslogger >= 1.2.10
    - dump >= 0.2.8
    - ansi-terminal >= 0.8.0.4

tests:
  stack-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - HUnit >= 1.6.0.0
    - gym-http-api # >= 0.1.0.0
    - aeson >= 1.3.1.1
