flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.4.0.0
- base-4.10.1.0
- base-compat-0.10.1
- containers-0.5.11.0
- exceptions-0.10.0
- http-api-data-0.3.8.1
- invertible-syntax-0.2.1
- servant-0.13.0.1
- servant-client-0.13.0.1
resolver: lts-11.15
# allow-newer: true
# allow-different-user: true
explicit-setup-deps:
  "*": true
